# GitHub Actions demo to create a directory listing for the repository files to publish to GitHub Pages

name: Demo Action

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Directory Listing Script
        run: php directory-listing.php

      - name: Recursive usage # (Optional)
        run: |
          cd src && php ../directory-listing.php
          cd icons && php ../../directory-listing.php

      - name: Set path label # (Optional)
        run: echo caendesilva/php-directory-listing@master > .dl-pathlabel

      - name: Commit Directory Listing
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add index.html src/index.html src/icons/index.html
          git commit -m "Update directory listing `${{ github.sha }}`"
          git push
